# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_service_provider',
            name='sp_address',
            field=models.CharField(max_length=40, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x95\x86\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
    ]
