# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='expand',
            field=models.ForeignKey(default=99999, null=True, on_delete=django.db.models.deletion.CASCADE, to='zhengzihui_app.tb_user_expand', verbose_name=b'\xe5\xaf\xb9\xe5\xba\x94\xe7\x9a\x84\xe6\x89\xa9\xe5\xb1\x95\xe8\xa1\xa8'),
        ),
    ]
