# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_companyuser',
            fields=[
                ('companyUserId', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7id')),
                ('companyUserName', models.CharField(max_length=100, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('companyUserPassword', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('companyUserCompanyName', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('companyUserCompanyLocation', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe4\xbd\x8d\xe7\xbd\xae')),
                ('companyUserCompanyAddress', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe5\x9c\xb0\xe5\x9d\x80')),
                ('companyUserCompanyCapital', models.CharField(max_length=100, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe8\xb5\x84\xe6\x9c\xac')),
                ('companyUserCompanyPeople', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe4\xba\xba\xe6\x95\xb0')),
                ('companyUserCompanyIndustry', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe8\xa1\x8c\xe4\xb8\x9a')),
                ('companyUserCompanyNature', models.CharField(max_length=100, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe6\x80\xa7\xe8\xb4\xa8')),
                ('companyUserContactName', models.CharField(max_length=40, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba\xe5\xa7\x93\xe5\x90\x8d')),
                ('companyUserPhone', models.CharField(max_length=40, verbose_name=b'\xe5\x9b\xba\xe8\xaf\x9d')),
                ('companyUserTelephone', models.CharField(max_length=40, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba')),
                ('companyUserEmail', models.EmailField(max_length=254, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe9\x82\xae\xe7\xae\xb1')),
            ],
        ),
        migrations.AlterField(
            model_name='tb_news',
            name='news_hot',
            field=models.IntegerField(choices=[(1, b'\xe7\x83\xad\xe7\x82\xb9\xe6\x96\xb0\xe9\x97\xbb'), (0, b'\xe9\x9d\x9e\xe7\x83\xad\xe7\x82\xb9\xe6\x96\xb0\xe9\x97\xbb')], default=0, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe7\x83\xad\xe7\x82\xb9\xe6\x96\xb0\xe9\x97\xbb'),
        ),
        migrations.AlterField(
            model_name='tb_service_provider',
            name='is_recommend',
            field=models.IntegerField(choices=[(1, b'\xe4\xbc\x98\xe5\x85\x88\xe6\x8e\xa8\xe8\x8d\x90(\xe5\xbd\x93\xe6\x9c\x89\xe7\x9b\xb8\xe5\x90\x8c\xe6\x8a\xa5\xe4\xbb\xb7\xe7\x9a\x84\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x95\x86\xef\xbc\x8c\xe6\x98\xaf\xe5\x90\xa6\xe4\xbc\x98\xe5\x85\x88\xe8\x80\x83\xe8\x99\x91\xe6\x8e\xa8\xe8\x8d\x90)'), (0, b'\xe4\xb8\x8d\xe4\xbc\x98\xe5\x85\x88\xe6\x8e\xa8\xe8\x8d\x90')], default=1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xbc\x98\xe5\x85\x88\xe6\x8e\xa8\xe8\x8d\x90'),
        ),
    ]
