# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_goods',
            name='goods_accept_endtime',
            field=models.DateTimeField(null=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe6\x8e\xa5\xe5\x8d\x95\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='tb_goods',
            name='goods_accept_starttime',
            field=models.DateTimeField(null=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x8e\xa5\xe5\x8d\x95\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='tb_goods',
            name='goods_awardafter',
            field=models.IntegerField(default=100, verbose_name=b'\xe7\x94\xb3\xe6\x8a\xa5\xe6\x88\x90\xe5\x8a\x9f\xe5\x90\x8e\xe5\xa5\x96\xe9\x87\x91'),
        ),
        migrations.AddField(
            model_name='tb_goods',
            name='goods_code',
            field=models.IntegerField(null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='tb_goods',
            name='goods_payahead',
            field=models.IntegerField(default=100, verbose_name=b'\xe9\xa6\x96\xe4\xbb\x98\xe9\x87\x91\xe9\xa2\x9d'),
        ),
    ]
