# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_order',
            name='has_pay',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x94\xaf\xe4\xbb\x98'),
        ),
    ]
