# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_customcompany',
            fields=[
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=b'\xe4\xbc\x81\xe4\xb8\x9aid')),
                ('custom_hangye', models.CharField(max_length=100, verbose_name=b'\xe8\xa1\x8c\xe4\xb8\x9a')),
                ('custom_bumen', models.CharField(max_length=100, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8')),
                ('custom_jiebie', models.CharField(max_length=100, verbose_name=b'\xe7\xba\xa7\xe5\x88\xab')),
                ('wanted_guquan', models.CharField(max_length=100, verbose_name=b'\xe8\x82\xa1\xe6\x9d\x83')),
                ('wanted_rongzi', models.CharField(max_length=100, verbose_name=b'\xe5\x80\xba\xe5\x88\xb8')),
                ('wanted_ziben', models.CharField(max_length=100, verbose_name=b'\xe8\xb5\x84\xe6\x9c\xac')),
                ('self_des', models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x87\xaa\xe8\xaf\x84')),
                ('item_des', models.CharField(max_length=100, null=True, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe8\xaf\x84\xe4\xbb\xb7')),
                ('self_file', models.FileField(null=True, upload_to=b'./upload')),
                ('item_file', models.FileField(null=True, upload_to=b'./upload')),
                ('conclusion', models.CharField(max_length=100, null=True, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe8\xaf\x84\xe4\xbb\xb7')),
            ],
        ),
    ]
