# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_goods',
            name='goods_successrate',
            field=models.IntegerField(default=50),
        ),
    ]
