# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0002_tb_customcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_shoucang_goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'ID')),
                ('user_id', models.IntegerField(verbose_name=b'\xe5\xaf\xb9\xe5\xba\x94\xe7\x94\xa8\xe6\x88\xb7\xe7\x9a\x84ID')),
                ('goods_id', models.IntegerField(verbose_name=b'\xe5\xaf\xb9\xe5\xba\x94\xe6\x9c\x8d\xe5\x8a\xa1\xe7\x9a\x84ID')),
            ],
        ),
        migrations.CreateModel(
            name='tb_shoucang_item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'ID')),
                ('user_id', models.IntegerField(verbose_name=b'\xe5\xaf\xb9\xe5\xba\x94\xe7\x94\xa8\xe6\x88\xb7\xe7\x9a\x84ID')),
                ('item_id', models.IntegerField(verbose_name=b'\xe5\xaf\xb9\xe5\xba\x94\xe9\xa1\xb9\xe7\x9b\xae\xe7\x9a\x84ID')),
            ],
        ),
    ]
