# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0002_auto_20161018_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_service_provider',
            name='chargeman_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba\xe9\x82\xae\xe7\xae\xb1'),
        ),
        migrations.AddField(
            model_name='tb_service_provider',
            name='chargeman_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AddField(
            model_name='tb_service_provider',
            name='chargeman_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba\xe7\x94\xb5\xe8\xaf\x9d'),
        ),
        migrations.AddField(
            model_name='tb_service_provider',
            name='con_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba\xe9\x82\xae\xe7\xae\xb1'),
        ),
        migrations.AddField(
            model_name='tb_service_provider',
            name='con_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba\xe7\x94\xb5\xe8\xaf\x9d'),
        ),
        migrations.AddField(
            model_name='tb_service_provider',
            name='short_intro',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x95\x86\xe7\xae\x80\xe4\xbb\x8b'),
        ),
    ]
