# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0002_tb_order_has_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_order',
            name='finish_percentage',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xae\x8c\xe6\x88\x90\xe8\xbf\x9b\xe5\xba\xa6'),
        ),
    ]
