# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0002_auto_20160719_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_order',
            name='item_name',
            field=models.CharField(max_length=1000, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='tb_order',
            name='order_state',
            field=models.IntegerField(choices=[(0, b'\xe5\xb7\xb2\xe5\x8f\x96\xe6\xb6\x88'), (1, b'\xe6\x9c\xaa\xe4\xbb\x98\xe6\xac\xbe'), (2, b'\xe5\xb7\xb2\xe4\xbb\x98\xe6\xac\xbe'), (3, b'\xe5\xb7\xb2\xe4\xb8\x8b\xe5\x8d\x95'), (4, b'\xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90')], default=1, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
