# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0003_tb_order_finish_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_notice',
            name='Notice_short_content',
            field=models.CharField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xac\xe5\x91\x8a\xe7\x9f\xad\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
