# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0003_auto_20160722_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_order',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x94\x9f\xe6\x88\x90\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
