# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0004_auto_20160722_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_order',
            name='delay_time',
            field=models.DateTimeField(null=True, verbose_name=b'\xe5\xbb\xb6\xe8\xbf\x9f\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='tb_order',
            name='final_time',
            field=models.DateTimeField(null=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe5\xae\x8c\xe6\x88\x90\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='tb_order',
            name='payment_time',
            field=models.DateTimeField(null=True, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98(\xe4\xbb\x98\xe6\xac\xbe)\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
