# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0004_auto_20161020_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='sp_inservice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privince', models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x9c\x81')),
                ('city', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\xb8\x82')),
                ('distr', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8c\xba')),
                ('xianfen', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\xbf\xe4\xbb\xbd')),
                ('sp_id', models.IntegerField(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x95\x86\xe7\x9a\x84id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
