# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0006_tb_balist_ba_ftime'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_back_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7id')),
                ('user_name', models.CharField(max_length=100, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('user_password', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('user_telephone', models.CharField(max_length=40, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
                ('user_email', models.EmailField(max_length=254, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe9\x82\xae\xe7\xae\xb1')),
                ('user_auth', models.IntegerField(choices=[(1, b'\xe9\x80\x9a\xe8\xbf\x87\xe9\xaa\x8c\xe8\xaf\x81'), (0, b'\xe9\xaa\x8c\xe8\xaf\x81\xe6\xb2\xa1\xe6\x9c\x89\xe9\x80\x9a\xe8\xbf\x87\xe6\x88\x96\xe8\x80\x85\xe6\xb2\xa1\xe6\x9c\x89\xe9\xaa\x8c\xe8\xaf\x81')], default=0, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe9\xaa\x8c\xe8\xaf\x81\xe7\x8a\xb6\xe6\x80\x81')),
                ('user_type', models.IntegerField(choices=[(2, b'\xe5\xae\xa2\xe6\x9c\x8d\xe4\xba\xba\xe5\x91\x98'), (1, b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xba\xba\xe5\x91\x98'), (0, b'\xe8\xb6\x85\xe7\xba\xa7\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')], default=2, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe7\x94\xa8\xe6\x88\xb7\xe7\xb1\xbb\xe5\x9e\x8b')),
            ],
            options={
                'verbose_name': '\u540e\u53f0\u7528\u6237',
                'verbose_name_plural': '\u540e\u53f0\u7528\u6237',
            },
        ),
    ]
