# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0007_tb_back_user'),
        ('zhengzihui_app', '0007_tb_goods_evaluation_location'),
    ]

    operations = [
    ]
