# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0009_linker_shareinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_item',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\xb8\x82'),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='distr',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8c\xba'),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='privince',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x9c\x81'),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='xianfen',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\xbf\xe4\xbb\xbd'),
        ),
    ]
