# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhengzihui_app', '0010_auto_20160919_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='push_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_item_id', models.IntegerField(verbose_name=b'\xe6\x8e\xa8\xe9\x80\x81\xe9\xa1\xb9\xe7\x9b\xae\xe7\x9a\x84id')),
                ('push_to_user', models.IntegerField(verbose_name=b'\xe6\x8e\xa8\xe9\x80\x81\xe5\x88\xb0\xe7\x9a\x84\xe7\x94\xa8\xe6\x88\xb7\xe7\x9a\x84id')),
            ],
        ),
    ]
